---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
checksum:
  enabled: true
  require_checksum: true
  supported_envs:
  - all
registries:
- type: standard
  ref: v4.108.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: ogham/exa@v0.10.1
- name: junegunn/fzf@0.44.1
- name: cli/cli@v2.40.1
- name: x-motemen/ghq@v1.4.2
- name: golang/go@go1.21.5
- name: jqlang/jq@jq-1.7.1
- name: neovim/neovim@v0.9.4
- name: starship/starship@v1.16.0
- name: ajeetdsouza/zoxide@v0.9.2
- name: mitsuhiko/rye@0.16.0
- name: volta-cli/volta@v1.1.1
- name: BurntSushi/ripgrep@14.0.3
- name: dylanaraps/neofetch@7.1.0
