---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.88.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: ogham/exa@v0.10.1
- name: junegunn/fzf@0.44.0
- name: cli/cli@v2.39.1
- name: x-motemen/ghq@v1.4.2
- name: golang/go@go1.21.4
- name: jqlang/jq@jq-1.7
- name: neovim/neovim@stable
- name: starship/starship@v1.16.0
- name: ajeetdsouza/zoxide@v0.9.2
- name: mitsuhiko/rye@0.15.2
- name: volta-cli/volta@v1.1.1
