---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
checksum:
  enabled: true
  require_checksum: true
  supported_envs:
  - all
registries:
- type: standard
  ref: v4.126.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: junegunn/fzf@0.46.0
- name: cli/cli@v2.43.1
- name: x-motemen/ghq@v1.4.2
- name: golang/go@go1.21.6
- name: jqlang/jq@jq-1.7.1
- name: neovim/neovim@v0.9.5
- name: starship/starship@v1.17.1
- name: ajeetdsouza/zoxide@v0.9.2
- name: mitsuhiko/rye@0.19.0
- name: volta-cli/volta@v1.1.1
- name: BurntSushi/ripgrep@14.1.0
- name: dylanaraps/neofetch@7.1.0
- name: eza-community/eza@v0.17.3
- name: tree-sitter/tree-sitter@v0.20.9
