'$schema' = 'https://starship.rs/config-schema.json'

add_newline = false
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$conda\
$cmd_duration\
$time\
$line_break\
$character"""

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'
vimcmd_symbol = '[\$](bold green)'

[hostname]
ssh_symbol = '\[ssh\]'                      # less escaped
format = '[$hostname$ssh_symbol]($style) '

[git_branch]
symbol = 'git '

[git_commit]
tag_symbol = ' tag '

[git_status]
ahead = '>'
behind = '<'
diverged = '<>'
renamed = 'r'
deleted = 'x'

[time]
disabled = false

[conda]
