'$schema' = 'https://starship.rs/config-schema.json'

add_newline = false
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character"""
right_format = """
$cmd_duration\
$time"""

[hostname]
ssh_symbol = '\[ssh\]'
format = '[$hostname$ssh_symbol]($style) '

[git_branch]
symbol = ''
truncation_length = 4

[git_commit]
tag_symbol = ' tag '

[git_status]
ahead = '>'
behind = '<'
diverged = '<>'
renamed = 'r'
deleted = 'x'

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'
vimcmd_symbol = '[\$](bold green)'

[time]
disabled = false
