theme = "catppuccin_latte"

[editor]
auto-save = true # TODO: 動いてる？
cursorline = true
cursorcolumn = true
true-color = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type", "read-only-indicator", "file-modification-indicator"]
mode.normal ="NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
tabpad = "."

[editor.indent-guides]
render = true

[keys.normal]
Z = { Z = ":wq" }

[keys.insert]
j = { k = "normal_mode" }
