# Use Deno on TypeScript

[[language]]
name = "typescript"
shebangs = ["node", "deno"]
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["typescript-language-server", "deno-lsp"]

[[language]]
name = "tsx"
shebangs = ["node", "deno"]
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["typescript-language-server", "deno-lsp"]

[language-server.typescript-language-server]
required-root-patterns = ["package.json"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
config = { deno = { enable = true } }
# required-root-patterns = ["deno.*"]

[[language]]
name = "svelte"
formatter = { command = "deno", args = ["fmt", "--unstable-component", "--ext", "svelte", "-"] }
auto-format = true

# Use rustfmt on Rust

[[language]]
name = "rust"
formatter = { command = "rustfmt", args = ["--edition", "2024"] }
auto-format = true

# Use Ruff on Python

[[language]]
name = "python"
language-servers = [
  { name = "pylsp", except-features = [
    "format",
  ] },
  { name = "ruff", only-features = ["format"] },
]
auto-format = true

[language-server.pylsp.config.pylsp]
plugins.pylsp_mypy.enabled = true
plugins.pylsp_mypy.live_mode = true

[language-server.ruff]
command = "ruff"
args = ["server"]
