[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc", "package.json"]
language-servers = ["typescript-language-server", "deno-lsp"]

[[language]]
name = "tsc"
roots = ["deno.json", "deno.jsonc", "package.json"]
language-servers = ["typescript-language-server", "deno-lsp"]

[language-server.typescript-language-server]
required-root-patterns = ["package.json"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
required-root-patterns = ["deno.*"]
