#!/bin/sh

commit_msg_path=$1
if ! grep -q -m 1 '^[^#[:space:]]' "$commit_msg_path"; then
	exit
fi

json_path=~/.gitmoji/gitmojis.json
if ! test -e $json_path; then
	curl -o gitmojis_path https://gitmoji.dev/api/gitmojis
fi

emoji=$(cat $json_path | jq -r '.[] | "\(.emoji) \(.code) \(.description)"' | fzf | awk '{print $2}')

if ! grep -q "^$emoji" "$commit_msg_path"; then
	sed -i "1s/^/$emoji /" "$commit_msg_path"
fi
