'$schema' = 'https://starship.rs/config-schema.json'

add_newline = false
palette = 'catppuccin_latte'
format = """
$username\
$hostname\
$shell\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character"""

[username]
style_user = 'bold yellow'
style_root = 'bold red'

[hostname]
ssh_symbol = '\[ssh\]'
format = '[$hostname$ssh_symbol]($style) '
style = 'bold green'

[directory]
truncation_length = 4
style = 'bold lavender'

[shell]
disabled = false
unknown_indicator = "MYTERY SHELL"
format = '[\[$indicator\]]($style) '
style = "sapphire bold"

[git_branch]
symbol = ''

[git_commit]
tag_symbol = ' tag '

[git_status]
ahead = '>'
behind = '<'
diverged = '<>'
renamed = 'r'
deleted = 'x'

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'
vimcmd_symbol = '[\$](bold green)'

# https://github.com/catppuccin/starship
[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
