# git
abbr --add 'g' 'git'
abbr --add 'G' 'git status'
abbr --add 'ga' 'git add --all --verbose'
abbr --add 'gc' 'git commit --verbose'
abbr --add 'gd' 'git diff'
abbr --add 'gdt' 'git difft'
abbr --add 'gD' 'git clean -df && git restore'
abbr --add 'gDS' 'git clean -df && git restore --staged'
abbr --add 'gf' 'git fetch'
abbr --add 'gl' 'git log --oneline'
abbr --add 'gm' 'git merge'
abbr --add 'gp' 'git pull'
abbr --add 'gpr' 'git pull --rebase'
abbr --add 'gP' 'git push'
abbr --add 'gP!' 'git push --force-with-lease --force-if-includes'
abbr --add 'gr' 'git rebase'
abbr --add 'gs' 'git switch --recurse-submodules'
abbr --add 'gt' 'git stash'
abbr --add 'gw' 'git wt'
abbr --add 'gwa' 'git-worktree-add-interactive | fish_cdp'

# docker
abbr --add 'd' 'docker'
abbr --add 'dc' 'docker compose'

# ls (eza)
abbr --add 'la' 'eza -al'
abbr --add 'll' 'eza -l'
abbr --add 'ls' 'eza'

# others
abbr --add 'bd' 'brew bundle dump --global --tap --formula -f'
abbr --add 'c' 'code .'
abbr --add 'cdf' 'fd -td | fzf || echo $PWD | fish_cdp'
abbr --add 'cr' 'echo ~/ghq/$(ghq list | fzf) | fish_cdp'
abbr --add 'e' '/mnt/c/Windows/explorer.exe .'
abbr --add 'ghb' 'gh browse'
abbr --add 'gol' 'golangci-lint'
abbr --add 'grm' 'rm -i $GOPATH/bin/$(ls $GOPATH/bin | fzf)'
abbr --add 'gg' 'ghq get'
abbr --add 'n' 'nvim'
abbr --add 'o' 'op run --'
abbr --add 'od' 'obsidian-daily-note'
abbr --add 'ou' 'obsidian-unique-note'
abbr --add 'pp' 'pnpm'
abbr --add 'sc' 'systemctl'
abbr --add 'za' 'zellij a -c $(basename $PWD)_$(date -I)'
abbr --add 'zj' 'zellij'

