name: Build utility

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go build -o dist/ parse_tmpl.go
      - uses: actions/upload-artifact@v3
        with:
          name: parse_tmpl_${{ matrix.os }}
          path: dist/parse_tmpl*
