name: Compile install script with Deno

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compile:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up envs for ${{ matrix.os }}
        shell: bash
        run: |
          set -x
          echo "Compiling for ${{ matrix.os }}"
          if [ ${{ matrix.os }} == "windows-latest" ]; then
            echo "SRC_PATH=./install_windows.ts" >> $GITHUB_ENV
            echo "DIST_PATH=./dist/install.exe" >> $GITHUB_ENV
          else
            echo "SRC_PATH=./install_unix.ts" >> $GITHUB_ENV
            echo "DIST_PATH=./dist/install" >> $GITHUB_ENV
          fi
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Compile install script for ${{ matrix.os }}
        run: deno compile --allow-all -o ${{ env.DIST_PATH }} ${{ env.SRC_PATH }}
      - uses: actions/upload-artifact@v4
        with:
          name: install-${{ matrix.os }}
          path: ${{ env.DIST_PATH }}
  deploy-pages:
    needs: compile
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Prepare dist folder
        run: |
          mkdir -p dist
          mv artifacts/install-macos-latest/install dist/install-macos
          mv artifacts/install-ubuntu-latest/install dist/install-ubuntu
          mv artifacts/install-windows-latest/install.exe dist/install-windows.exe
      - name: Upload an artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: dist
      - uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
