name: Generate setting files from templates

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  generate:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Generate setting files from templates
        run: |
          go run parse_tmpl.go
      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "action@github.com"
          git add .
          git commit -m "[skip ci] Generate setting files from templates"
      - name: Push changes
        run: |
          git push
