name: Generate config from templates

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  generate:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - name: Rebase to main
        run: |
          git fetch origin main
          git rebase origin/main
      - name: Generate config from templates
        run: |
          go run parse_tmpl.go
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "${{ matrix.os }}: Generate config from templates"
