name: update aqua checksum

env:
  AQUA_VERSION: v2.16.4 # renovate: depName=aquaproj/aqua
  AQUA_WORKING_DIRECTORY: common/config/aquaproj-aqua

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ${{env.AQUA_WORKING_DIRECTORY}}/*
      - .github/workflows/update-checksum.yaml

jobs:
  update-aqua-checksum:
    uses: aquaproj/update-checksum-workflow/.github/workflows/update-checksum.yaml@main
    permissions:
      contents: read
    with:
      aqua_version: ${{env.AQUA_VERSION}}
      working_directory: ${{env.AQUA_WORKING_DIRECTORY}}
      prune: true
