name: update aqua checksum

on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - "common/aquaproj-aqua/*"
      - ".github/workflows/update-checksum.yaml"
  workflow_dispatch:

jobs:
  update-aqua-checksum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/cache@v4
        with:
          path: ~/.local/share/aquaproj-aqua
          key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('**/aqua.yaml')}}
          restore-keys: |
            v1-aqua-installer-${{runner.os}}-
      - uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.30.0
          working_directory: common/aquaproj-aqua
      - run: aqua update-checksum -deep -prune
        working-directory: common/aquaproj-aqua
      - run: git diff --exit-code
        id: diff
        continue-on-error: true
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit --author . -m "chore(aqua): update checksum for #$PR_NUM"
          git push origin
        if: steps.diff.outcome == 'failure'
        env:
          PR_NUM: ${{ github.event.number}}
      - run: aqua install --all --only-link

  approve:
    runs-on: ubuntu-latest
    needs: update-aqua-checksum
    if: "github.event.pull_request.user.login == 'renovate[bot]' && contains(github.event.pull_request.body, ' **Automerge**: Enabled.')"
    steps:
      - uses: actions/checkout@v4
      - run: gh pr review ${{ github.event.number }} --approve
        env:
          GITHUB_TOKEN: ${{ github.token }}
