name: update aqua checksum

on:
  pull_request:
    paths:
      - "common/config/aquaproj-aqua/aqua.yaml"
      - "common/config/aquaproj-aqua/aqua-checksum.json"
      - ".github/workflows/update-checksum.yaml"
  workflow_dispatch:

jobs:
  update-aqua-checksum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/aquaproj-aqua
          key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('**/aqua.yaml')}}
          restore-keys: |
            v1-aqua-installer-${{runner.os}}-${{runner.arch}}-
      - uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.21.3 # renovate: depName=aquaproj/aqua
          working_directory: common/config/aquaproj-aqua
      - run: aqua update-checksum -deep -prune
        working-directory: common/config/aquaproj-aqua
      - run: git diff --exit-code
        id: diff
        continue-on-error: true
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit --author . -m "chore(aqua): update checksum"
          git push origin
        if: steps.diff.outcome == 'failure'

  check-aqua-install:
    runs-on: ubuntu-latest
    needs: update-aqua-checksum
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/aquaproj-aqua
          key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('**/aqua.yaml')}}
          restore-keys: |
            v1-aqua-installer-${{runner.os}}-${{runner.arch}}-
      - uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.21.3 # renovate: depName=aquaproj/aqua
          working_directory: common/config/aquaproj-aqua
      - name: Check aqua lazy install on global
        run: aqua install -a -l
