name: update aqua checksum

on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - "common/config/aquaproj-aqua/*"
      - ".github/workflows/update-checksum.yaml"

jobs:
  update-aqua-checksum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/aquaproj-aqua
          key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('**/aqua.yaml')}}
          restore-keys: |
            v1-aqua-installer-${{runner.os}}-${{runner.arch}}-
      - uses: aquaproj/aqua-installer@v2.2.0 # renovate: depName=aquaproj/aqua-installer
        with:
          aqua_version: v2.16.4 # renovate: depName=aquaproj/aqua
          working_directory: common/config/aquaproj-aqua
      - run: aqua update-checksum -deep -prune
        working-directory: common/config/aquaproj-aqua
      - run: git diff --exit-code
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "chore(aqua): update checksum"
          git push
