name: update aqua checksum

on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - "common/config/aquaproj-aqua/*"
      - ".github/workflows/update-checksum.yaml"

jobs:
  update-aqua-checksum:
    uses: "ras0q/update-checksum-workflow/.github/workflows/update-checksum.yaml@main"
    permissions:
      contents: "read"
    with:
      aqua_version: "v2.17.3" # renovate: depName=aquaproj/aqua
      working_directory: "common/config/aquaproj-aqua"
      prune: true
